### ISSUE TITLE
Move documentation to GitHub

### ISSUE THREAD

**Issue by helmbold** [jmp75/rClr#29]
Since CodePlex is shutting down, I suggest to move all [documenation hosted at CodePlex](https://r2clr.codeplex.com/documentation) to GitHub.

[CodePlex will be finally shut down on 2017-12-17](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/).

**Comment by atifaziz** [comment]
Done:

- [Build Instructions](https://github.com/jmp75/rClr/wiki/Build-Instructions.md)
- [Documentation](https://github.com/jmp75/rClr/wiki/Documentation.md)
- [FAQ](https://github.com/jmp75/rClr/wiki/FAQ.md)
- [Handling Simple Data](https://github.com/jmp75/rClr/wiki/Handling-Simple-Data.md)
- [Hello World](https://github.com/jmp75/rClr/wiki/Hello-World.md)
- [Home](https://github.com/jmp75/rClr/wiki/Home.md)
- [Installing R Packages](https://github.com/jmp75/rClr/wiki/Installing-R-Packages.md)
- [Notes on CRAN](https://github.com/jmp75/rClr/wiki/Notes-on-CRAN.md)
- [Quick Start](https://github.com/jmp75/rClr/wiki/Quick-Start.md)
- [Release Checklist](https://github.com/jmp75/rClr/wiki/Release-Checklist.md)
- [Roadmap](https://github.com/jmp75/rClr/wiki/Roadmap.md)
- [Spatial Temporal Model](https://github.com/jmp75/rClr/wiki/Spatial-Temporal-Model.md)
- [Technical Notes](https://github.com/jmp75/rClr/wiki/Technical-Notes.md)
- [Technical Reference](https://github.com/jmp75/rClr/wiki/Technical-Reference.md)
- [Troubleshooting](https://github.com/jmp75/rClr/wiki/Troubleshooting.md)

Hope this helped.

**Comment by helmbold** [comment]
Thanks!
