### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by screig** [jmp75/rClr#9]
Hi 

I am trying to follow the instructions for downloading:

    # Optionally you may remove a prior package
    remove.packages('rClr')
    library(devtools)
    install_github("jmp75/rClr", build_vignettes=TRUE)

I'm not sure but is this error on myside?

    Downloading github repo jmp75/rClr@master
    Error in curl::curl_fetch_memory(url, handle = handle) : 
      Peer certificate cannot be authenticated with given CA certificates

**Comment by jmp75** [comment]
I note that the question went through stackoverflow and one reply is marked as answer - need to update documentation. [Stackoverflow thread ](http://stackoverflow.com/questions/31293325/r-install-github-fails)
